<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('orders')->insert([
            [
                'user_id' => 1,
                'type' => 'Margherita',
                'base' => 'Classic',
                'name' => 'Margherita',
                'price' => 12,
                'toppings' => json_encode(['mozzarella', 'basil']),
                'image_url' => '/img/pizza1.png',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'user_id' => 2,
                'type' => 'Pepperoni',
                'base' => 'Thin',
                'name' => 'Pepperoni Feast',
                'price' => 15,
                'toppings' => json_encode(['mozzarella', 'pepperoni']),
                'image_url' => '/img/pizza2.png',
                'created_at' => now()->subDays(9),
                'updated_at' => now()->subDays(9),
            ],
            [
                'user_id' => 3,
                'type' => 'Veggie',
                'base' => 'Classic',
                'name' => 'Garden Veggie',
                'price' => 13,
                'toppings' => json_encode(['mozzarella', 'peppers', 'onions', 'olives']),
                'image_url' => '/img/pizza3.png',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8),
            ],
            [
                'user_id' => 4,
                'type' => 'Hawaiian',
                'base' => 'Thick',
                'name' => 'Hawaiian Delight',
                'price' => 16,
                'toppings' => json_encode(['mozzarella', 'ham', 'pineapple']),
                'image_url' => '/img/pizza4.png',
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(7),
            ],
            [
                'user_id' => 5,
                'type' => 'Volcano',
                'base' => 'Thin & Crispy',
                'name' => 'Volcano Heat',
                'price' => 17,
                'toppings' => json_encode(['mozzarella', 'chili', 'pepperoni']),
                'image_url' => '/img/pizza5.png',
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(6),
            ],
            [
                'user_id' => 1,
                'type' => 'Margherita',
                'base' => 'Garlic Crust',
                'name' => 'Garlic Margherita',
                'price' => 14,
                'toppings' => json_encode(['mozzarella', 'basil', 'garlic']),
                'image_url' => '/img/pizza6.png',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'user_id' => 2,
                'type' => 'Veg Supreme',
                'base' => 'Classic',
                'name' => 'Supreme Veg',
                'price' => 15,
                'toppings' => json_encode(['mozzarella', 'mushrooms', 'peppers', 'olives']),
                'image_url' => '/img/pizza7.png',
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'user_id' => 3,
                'type' => 'Pepperoni',
                'base' => 'Cheesy Crust',
                'name' => 'Cheesy Pepperoni',
                'price' => 17,
                'toppings' => json_encode(['mozzarella', 'pepperoni', 'extra cheese']),
                'image_url' => '/img/pizza8.png',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'user_id' => 4,
                'type' => 'Hawaiian',
                'base' => 'Thin & Crispy',
                'name' => 'Crispy Hawaiian',
                'price' => 16,
                'toppings' => json_encode(['mozzarella', 'ham', 'pineapple']),
                'image_url' => '/img/pizza9.png',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => 5,
                'type' => 'Volcano',
                'base' => 'Thick',
                'name' => 'Lava Blast',
                'price' => 18,
                'toppings' => json_encode(['mozzarella', 'chili', 'garlic']),
                'image_url' => '/img/pizza10.png',
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
            [
                'user_id' => 1,
                'type' => 'Pepperoni',
                'base' => 'Classic',
                'name' => 'Pepperoni Feast',
                'price' => 15,
                'toppings' => json_encode(['pepperoni', 'mozzarella']),
                'image_url' => '/img/pizza2.png',
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(15),
            ],
            [
                'user_id' => 2,
                'type' => 'Margherita',
                'base' => 'Thin',
                'name' => 'Margherita',
                'price' => 12,
                'toppings' => json_encode(['basil', 'mozzarella']),
                'image_url' => '/img/pizza1.png',
                'created_at' => now()->subDays(14),
                'updated_at' => now()->subDays(14),
            ],
            [
                'user_id' => 3,
                'type' => 'Hawaiian',
                'base' => 'Classic',
                'name' => 'Hawaiian Delight',
                'price' => 16,
                'toppings' => json_encode(['ham', 'pineapple', 'mozzarella']),
                'image_url' => '/img/pizza4.png',
                'created_at' => now()->subDays(13),
                'updated_at' => now()->subDays(13),
            ],
            [
                'user_id' => 4,
                'type' => 'Veggie',
                'base' => 'Garlic Crust',
                'name' => 'Garden Veggie',
                'price' => 13,
                'toppings' => json_encode(['peppers', 'onions', 'olives', 'mozzarella']),
                'image_url' => '/img/pizza3.png',
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(12),
            ],
            [
                'user_id' => 5,
                'type' => 'Volcano',
                'base' => 'Thick',
                'name' => 'Volcano Heat',
                'price' => 17,
                'toppings' => json_encode(['chili', 'pepperoni', 'mozzarella']),
                'image_url' => '/img/pizza5.png',
                'created_at' => now()->subDays(11),
                'updated_at' => now()->subDays(11),
            ],
            [
                'user_id' => 1,
                'type' => 'Veg Supreme',
                'base' => 'Classic',
                'name' => 'Supreme Veg',
                'price' => 15,
                'toppings' => json_encode(['mushrooms', 'peppers', 'olives', 'mozzarella']),
                'image_url' => '/img/pizza7.png',
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(20),
            ],
            [
                'user_id' => 2,
                'type' => 'Pepperoni',
                'base' => 'Cheesy Crust',
                'name' => 'Cheesy Pepperoni',
                'price' => 17,
                'toppings' => json_encode(['pepperoni', 'extra cheese', 'mozzarella']),
                'image_url' => '/img/pizza8.png',
                'created_at' => now()->subDays(19),
                'updated_at' => now()->subDays(19),
            ],
            [
                'user_id' => 3,
                'type' => 'Margherita',
                'base' => 'Thin & Crispy',
                'name' => 'Garlic Margherita',
                'price' => 14,
                'toppings' => json_encode(['basil', 'garlic', 'mozzarella']),
                'image_url' => '/img/pizza6.png',
                'created_at' => now()->subDays(18),
                'updated_at' => now()->subDays(18),
            ],
            [
                'user_id' => 4,
                'type' => 'Hawaiian',
                'base' => 'Thin & Crispy',
                'name' => 'Crispy Hawaiian',
                'price' => 16,
                'toppings' => json_encode(['ham', 'pineapple', 'mozzarella']),
                'image_url' => '/img/pizza9.png',
                'created_at' => now()->subDays(17),
                'updated_at' => now()->subDays(17),
            ],
            [
                'user_id' => 5,
                'type' => 'Volcano',
                'base' => 'Classic',
                'name' => 'Lava Blast',
                'price' => 18,
                'toppings' => json_encode(['chili', 'garlic', 'mozzarella']),
                'image_url' => '/img/pizza10.png',
                'created_at' => now()->subDays(16),
                'updated_at' => now()->subDays(16),
            ],
            [
                'user_id' => 1,
                'type' => 'Margherita',
                'base' => 'Classic',
                'name' => 'Margherita',
                'price' => 12,
                'toppings' => json_encode(['basil', 'mozzarella']),
                'image_url' => '/img/pizza1.png',
                'created_at' => now()->subDays(25),
                'updated_at' => now()->subDays(25),
            ],
            [
                'user_id' => 2,
                'type' => 'Pepperoni',
                'base' => 'Thin',
                'name' => 'Pepperoni Feast',
                'price' => 15,
                'toppings' => json_encode(['pepperoni', 'mozzarella']),
                'image_url' => '/img/pizza2.png',
                'created_at' => now()->subDays(24),
                'updated_at' => now()->subDays(24),
            ],
            [
                'user_id' => 3,
                'type' => 'Veggie',
                'base' => 'Classic',
                'name' => 'Garden Veggie',
                'price' => 13,
                'toppings' => json_encode(['peppers', 'onions', 'olives', 'mozzarella']),
                'image_url' => '/img/pizza3.png',
                'created_at' => now()->subDays(23),
                'updated_at' => now()->subDays(23),
            ],
            [
                'user_id' => 4,
                'type' => 'Veg Supreme',
                'base' => 'Garlic Crust',
                'name' => 'Supreme Veg',
                'price' => 15,
                'toppings' => json_encode(['mushrooms', 'peppers', 'olives', 'mozzarella']),
                'image_url' => '/img/pizza7.png',
                'created_at' => now()->subDays(22),
                'updated_at' => now()->subDays(22),
            ],
            [
                'user_id' => 5,
                'type' => 'Hawaiian',
                'base' => 'Thick',
                'name' => 'Hawaiian Delight',
                'price' => 16,
                'toppings' => json_encode(['ham', 'pineapple', 'mozzarella']),
                'image_url' => '/img/pizza4.png',
                'created_at' => now()->subDays(21),
                'updated_at' => now()->subDays(21),
            ],
            [
                'user_id' => 1,
                'type' => 'Volcano',
                'base' => 'Thin & Crispy',
                'name' => 'Volcano Heat',
                'price' => 17,
                'toppings' => json_encode(['chili', 'pepperoni', 'mozzarella']),
                'image_url' => '/img/pizza5.png',
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(30),
            ],
            [
                'user_id' => 2,
                'type' => 'Margherita',
                'base' => 'Cheesy Crust',
                'name' => 'Garlic Margherita',
                'price' => 14,
                'toppings' => json_encode(['basil', 'garlic', 'mozzarella']),
                'image_url' => '/img/pizza6.png',
                'created_at' => now()->subDays(29),
                'updated_at' => now()->subDays(29),
            ],
            [
                'user_id' => 3,
                'type' => 'Pepperoni',
                'base' => 'Classic',
                'name' => 'Cheesy Pepperoni',
                'price' => 17,
                'toppings' => json_encode(['pepperoni', 'extra cheese', 'mozzarella']),
                'image_url' => '/img/pizza8.png',
                'created_at' => now()->subDays(28),
                'updated_at' => now()->subDays(28),
            ],
            [
                'user_id' => 4,
                'type' => 'Hawaiian',
                'base' => 'Thin & Crispy',
                'name' => 'Crispy Hawaiian',
                'price' => 16,
                'toppings' => json_encode(['ham', 'pineapple', 'mozzarella']),
                'image_url' => '/img/pizza9.png',
                'created_at' => now()->subDays(27),
                'updated_at' => now()->subDays(27),
            ],
            [
                'user_id' => 5,
                'type' => 'Volcano',
                'base' => 'Thick',
                'name' => 'Lava Blast',
                'price' => 18,
                'toppings' => json_encode(['chili', 'garlic', 'mozzarella']),
                'image_url' => '/img/pizza10.png',
                'created_at' => now()->subDays(26),
                'updated_at' => now()->subDays(26),
            ],
        ]);
    }
}
